//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Capa_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class adm_usuarioreferencia
    {
        public byte id { get; set; }
        public int usuario { get; set; }
        public int referencia { get; set; }
        public string valor { get; set; }
    
        public virtual adm_referencia adm_referencia { get; set; }
        public virtual adm_usuario adm_usuario { get; set; }
    }
}
