//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Capa_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class adm_empresa
    {
        public adm_empresa()
        {
            this.adm_empresareferencia = new HashSet<adm_empresareferencia>();
            this.adm_representante = new HashSet<adm_representante>();
            this.inv_productoempresa = new HashSet<inv_productoempresa>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string pais { get; set; }
    
        public virtual ICollection<adm_empresareferencia> adm_empresareferencia { get; set; }
        public virtual ICollection<adm_representante> adm_representante { get; set; }
        public virtual ICollection<inv_productoempresa> inv_productoempresa { get; set; }
    }
}
