//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Capa_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class adm_usuario
    {
        public adm_usuario()
        {
            this.adm_representante = new HashSet<adm_representante>();
            this.adm_usuarioreferencia = new HashSet<adm_usuarioreferencia>();
        }
    
        public int id { get; set; }
        public string loggin { get; set; }
        public int ci { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
    
        public virtual adm_administrador adm_administrador { get; set; }
        public virtual adm_cliente adm_cliente { get; set; }
        public virtual ICollection<adm_representante> adm_representante { get; set; }
        public virtual ICollection<adm_usuarioreferencia> adm_usuarioreferencia { get; set; }
    }
}
