//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Capa_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class adm_referencia
    {
        public adm_referencia()
        {
            this.adm_empresareferencia = new HashSet<adm_empresareferencia>();
            this.adm_usuarioreferencia = new HashSet<adm_usuarioreferencia>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<adm_empresareferencia> adm_empresareferencia { get; set; }
        public virtual ICollection<adm_usuarioreferencia> adm_usuarioreferencia { get; set; }
    }
}
