//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Capa_Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IntellibusinessEntities : DbContext
    {
        public IntellibusinessEntities()
            : base("name=IntellibusinessEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adm_administrador> adm_administrador { get; set; }
        public virtual DbSet<adm_cliente> adm_cliente { get; set; }
        public virtual DbSet<adm_empresa> adm_empresa { get; set; }
        public virtual DbSet<adm_empresareferencia> adm_empresareferencia { get; set; }
        public virtual DbSet<adm_referencia> adm_referencia { get; set; }
        public virtual DbSet<adm_representante> adm_representante { get; set; }
        public virtual DbSet<adm_usuario> adm_usuario { get; set; }
        public virtual DbSet<adm_usuarioreferencia> adm_usuarioreferencia { get; set; }
        public virtual DbSet<inv_escalar> inv_escalar { get; set; }
        public virtual DbSet<inv_imagenproducto> inv_imagenproducto { get; set; }
        public virtual DbSet<inv_numerico> inv_numerico { get; set; }
        public virtual DbSet<inv_producto> inv_producto { get; set; }
        public virtual DbSet<inv_productoempresa> inv_productoempresa { get; set; }
        public virtual DbSet<inv_productonumerico> inv_productonumerico { get; set; }
        public virtual DbSet<ven_detalleventa> ven_detalleventa { get; set; }
        public virtual DbSet<mrk_descuento> mrk_descuento { get; set; }
        public virtual DbSet<ven_venta> ven_venta { get; set; }
        public virtual DbSet<inv_valorescalar> inv_valorescalar { get; set; }
    }
}
