//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Capa_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class inv_productonumerico
    {
        public int producto { get; set; }
        public int propiedadnumerica { get; set; }
        public float valor { get; set; }
    
        public virtual inv_numerico inv_numerico { get; set; }
        public virtual inv_producto inv_producto { get; set; }
    }
}
