//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Capa_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class inv_valorescalar
    {
        public inv_valorescalar()
        {
            this.inv_producto = new HashSet<inv_producto>();
        }
    
        public int id { get; set; }
        public int escalar { get; set; }
        public string valor { get; set; }
    
        public virtual inv_escalar inv_escalar { get; set; }
        public virtual ICollection<inv_producto> inv_producto { get; set; }
    }
}
